#!/bin/bash

rm -f /dev/pacman
rm -f /dev/pacman1
rm -f /dev/pacman2
rmmod pacman
rm -f pacman.o
make
insmod ./pacman.o
mknod /dev/pacman c 254 0
mknod /dev/pacman1 c 254 1
mknod /dev/pacman2 c 254 2
